server:
    port: 0
product:
  discount: 35%
management:
  endpoints:
    web:
      exposure:
        include: "*"
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest